#!/bin/bash

# setup environment for runing
[ "${LGI_ROOT}" ] || LGI_ROOT="`cd \`dirname $0\` && pwd`"
[ "${LGI_PID_FILE}" ] || LGI_PID_FILE="${LGI_ROOT}/LGI.pid"
[ "${LGI_CONFIG}" ] || LGI_CONFIG="${LGI_ROOT}/LGI.cfg"
export LGI_ROOT LGI_PID_FILE LGI_CONFIG
PATH="$PATH:${LGI_ROOT}/bin"
LD_LIBRARY_PATH="${LGI_ROOT}/lib"
export PATH LD_LIBRARY_PATH

cd "${LGI_ROOT}"

# run the LGI daemon
echo Starting the LGI daemon...
"${LGI_ROOT}/bin/LGI_daemon" ${LGI_OPTIONS} "${LGI_CONFIG}" &
PID=$!
echo ${PID} >"${LGI_PID_FILE}"
wait ${PID}
exit $?

